// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHLjZzfzkXjJeU7R2BuzHU932rfkSDpGw',
    appId: '1:35479366652:web:1c2e6135ec324f173d6079',
    messagingSenderId: '35479366652',
    projectId: 'jeetendra-soni-portfolio',
    authDomain: 'jeetendra-soni-portfolio.firebaseapp.com',
    storageBucket: 'jeetendra-soni-portfolio.firebasestorage.app',
    measurementId: 'G-FP82NS31SZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq4hUKFc5HcLGDfHIpOPdVdicSyhfK-00',
    appId: '1:35479366652:android:6eded4435bc9270f3d6079',
    messagingSenderId: '35479366652',
    projectId: 'jeetendra-soni-portfolio',
    storageBucket: 'jeetendra-soni-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK22Aqq-TdGWRWgQJe9jDYc0PplvEGaGs',
    appId: '1:35479366652:ios:185752caad62fa3c3d6079',
    messagingSenderId: '35479366652',
    projectId: 'jeetendra-soni-portfolio',
    storageBucket: 'jeetendra-soni-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.jeetendraPortfolio',
  );
}
